/*
 * usbd_msc_hid_core.h
 *
 *  Created on: Mar 2, 2021
 *      Author: radhwen.zorgui
 */

#ifndef ST_STM32_USB_DEVICE_LIBRARY_CLASS_MSC_HID_INC_USBD_MSC_HID_CORE_H_
#define ST_STM32_USB_DEVICE_LIBRARY_CLASS_MSC_HID_INC_USBD_MSC_HID_CORE_H_



#endif /* ST_STM32_USB_DEVICE_LIBRARY_CLASS_MSC_HID_INC_USBD_MSC_HID_CORE_H_ */
